### ISSUE TITLE
Ansible Galaxy doesn't support organizations with '-' in the name

### ISSUE THREAD

**Issue by oybed** [redhat-cop/casl-galaxy#2]
In attempt to build an Ansible Galaxy collection to publish, it won't currently let us publish due to the fact that our org name has a `-` in it - i.e.: `redhat-cop`. We are discussing alternatives, including using alternative names like `redhatcop`, `rhcop`, `redhat_cop`, but have not landed on a solution yet. This issue is to capture the fact that we are currently blocked from publishing the content. 

Related Ansible Galaxy issue can be found here:
https://github.com/ansible/galaxy/issues/779

@sabre1041 @etsauer @tylerauerbeck @garethahealy @pabrahamsson FYI

**Comment by etsauer** [comment]
I don't fully understand this change, as there are many many repos and orgs that contain hyphens. Why is this suddenly not being supported?

**Comment by oybed** [comment]
@etsauer I believe the above linked galaxy issue has the details, but to summarize (from one of the last replies to the above issue: 

> As we move toward Mazer and changing the way Ansible content is installed to the local filesystem, path and content names are expected to be Python compatible. So for this reason, we will no longer support '-' in namespace, repository and content names.

From a technical perspective, when attempting to publish an Ansible Galaxy collection it fails since it uses the dashes as a delimiter. Hence the tool/galaxy web site fails to parse the collection name if dashes are part of it. Since there is logic in place to match name and organizations in Ansible galaxy based on the filename, it *has* to be named `redhat-cop-<collection>-<version>` in our case, and hence uses `redhat` as the namespace/org name,  `cop` as the collection name and the collection name the version. ... which just errors out - for example:

```
> ansible-galaxy collection publish ./redhat-cop-casl_galaxy-0.1.0.tar.gz --api-key=...
: 
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Invalid filename. Expected: {namespace}-{name}-{version}.tar.gz Code: invalid)
```

**Comment by garethahealy** [comment]
archiving
